version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./ailink_at:/app/ailink_at
      - ./data:/app/data
    environment:
      - TELNYX_API_KEY=${TELNYX_API_KEY}
      - TELNYX_MESSAGING_PROFILE_ID=${TELNYX_MESSAGING_PROFILE_ID}